// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzj4CSkFJ8uZ27nmkY_ilNIVOkf14J06Y',
    appId: '1:27080870506:web:3face3767efdf966355813',
    messagingSenderId: '27080870506',
    projectId: 'gestionestudiante-5ced1',
    authDomain: 'gestionestudiante-5ced1.firebaseapp.com',
    storageBucket: 'gestionestudiante-5ced1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg-CM4h-wkj4Cb02DZ7MDIsmwoCIqSXkk',
    appId: '1:27080870506:android:08b4e2d39f71bccf355813',
    messagingSenderId: '27080870506',
    projectId: 'gestionestudiante-5ced1',
    storageBucket: 'gestionestudiante-5ced1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAseFrH8y4nGY_soIspiXiA_6jTNI1nLR8',
    appId: '1:27080870506:ios:2c59cb7e65e51e6c355813',
    messagingSenderId: '27080870506',
    projectId: 'gestionestudiante-5ced1',
    storageBucket: 'gestionestudiante-5ced1.appspot.com',
    iosBundleId: 'com.sysestudiantes.sysGestion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAseFrH8y4nGY_soIspiXiA_6jTNI1nLR8',
    appId: '1:27080870506:ios:34a97cd52162a359355813',
    messagingSenderId: '27080870506',
    projectId: 'gestionestudiante-5ced1',
    storageBucket: 'gestionestudiante-5ced1.appspot.com',
    iosBundleId: 'com.sysestudiantes.sysGestion.RunnerTests',
  );
}
